#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
clear

#Check Root
[ $(id -u) != "0" ] && { echo "Error: You must be root to run this script"; exit 1; }

ip link set gre1 down
ip tunnel del gre1

# config

read -p "设置隧道名称:" gre_name
read -p "输入本地ip:" local_ip
read -p "输入远程ip:" remote_ip
read -p "设置本机内网ip:" local
read -p "设置远程内网ip:" remote


ip tunnel add ${gre_name} mode gre remote ${remote_ip} local ${local_ip} ttl 255
ip link set ${gre_name} up
ip addr add ${local} peer ${remote} dev gre1
